### ISSUE TITLE
Fondamento Design Tokens: immagini da aggiornare

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#1009]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

FYI @zetareticoli vanno ri-esportate tutte le immagini del fondamento [Design Tokens](https://designers.italia.it/design-system/fondamenti/design-tokens/) senza bordo. Il bordo grigio e il 'rounded' essendo ora gestito via css risulta infatti doppio.  

![immagine](https://github.com/italia/designers.italia.it/assets/6736103/7d6776d6-884a-4689-aefa-f9cf781392e5)

### Perché

Outdated images.

**Comment by zetareticoli** [comment]
@Fupete non ritrovo il file sorgente su Figma 😔
