### ISSUE TITLE
Aggiornamento pagina progetto dei Siti web delle PA

### ISSUE THREAD

**Issue by francescozaia** [italia/designers.italia.it#101]
La pagina https://designers.italia.it/progetti/siti-web-pa/ non è aggiornata da tempo, ci sono progetti più interessanti da mostrare usciti di recente, tra cui:
- https://www.comune.fi.it/ (Gennaio 2018)
- http://www.politicheeuropee.gov.it/ (Gennaio 2018)
- http://www.regione.emilia-romagna.it/ (Febbraio 2018)

**Comment by vaibhavdaren** [comment]
i would like to work on this @francescozaia . Please assign me this.

mi piacerebbe lavorare su questo @francescozaia. Per favore assegnami questo

**Comment by roby986** [comment]
Inoltre i siti indicati fanno riferimento alle prime versioni delle LG, rischiando così di creare confusione.
Aggiungo che il sito della regione Sardegna è in realtà un prototipo che è stato da tempo sostituito con quello attualmente online.

**Comment by francescozaia** [comment]
Si è deciso di rimuovere quella pagina a breve, in quanto non particolarmente significativa e onerosa da mantenere.
