### ISSUE TITLE
Tooltip z-index issue on design system section. 

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#1038]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

There is a z-index issue with tooltips overlapped by design system navigation sidebar. See image. 

![issue](https://github.com/italia/designers.italia.it/assets/6736103/1129442a-385c-47f7-9bdd-33bcf53b90b6)

### Why

It is a bug. 

### Context

Maybe a regression inserted by https://github.com/italia/designers.italia.it/commit/859d90506fcf934bd45b704ea9ec18533aa80176 @bfabio @Lorenzo-Pappalardo ?

**Comment by Malay-dev** [comment]
Hey @Fupete, I would like to work on this issue... Please assign it to me..

**Comment by Lorenzo-Pappalardo** [comment]
Hi @Fupete,

I have identified a solution although I am not sure whether it can actually be adopted as it changes the bootstrap css class for the tooltip.
I am attaching some screenshots below:

![image](https://github.com/italia/designers.italia.it/assets/56509174/4516d3cd-9f4a-42c7-add5-6e87c1faf66b)
![image](https://github.com/italia/designers.italia.it/assets/56509174/5d04d014-06a4-4d51-9456-348c4d2daa4a)

A new css class could be added upon creation of the tooltip node to override the default z-index value, without altering the original bootstrap class.

**Comment by Fupete** [comment]
I also discovered that we have another z-index bug, unfortunately also a regression of https://github.com/italia/designers.italia.it/commit/859d90506fcf934bd45b704ea9ec18533aa80176.

Example: if you load the page https://designers.italia.it/design-system/come-iniziare/ and open the megamenu (without touching the scrollbar first) you get this: 
![immagine](https://github.com/italia/designers.italia.it/assets/6736103/1d247840-a710-4aa3-bb3d-d14cd4140944)

I'm starting to think whether it might not be better to revert this https://github.com/italia/designers.italia.it/commit/859d90506fcf934bd45b704ea9ec18533aa80176 and solve the z-index problem of "Back to top" in other ways? 

WDYT @bfabio @astagi @Lorenzo-Pappalardo ?

**Comment by bfabio** [comment]
My feeling is: https://github.com/italia/designers.italia.it/pull/1042#issuecomment-1790854976

I think using `z-index` in "client code" (a site) is a symptom we're doing something wrong.

**Comment by Fupete** [comment]
In principle I agree with you @bfabio and I don't know if the "z-index: auto" on the sidebar was used in the beginning to fix some Bootstrap Italy quirks 🤷. But still: we are stacking a lot of layers on the front-end, so some sort of z-index adjustment might be needed. 

That said, the question now is how to fix it without breaking anything else.... The megamenu under the sidebar is a fairly visible regression bug, as are the tooltips. I preferred the back to top under the cover images as before, I must say.

**Comment by bfabio** [comment]
I'd say, let Boostrap Italia drive on that. It should define all the components with the proper stacking and z-index, and if we use something in the site that isn't from BI (we shoudn't, in general), let's use a variable from BI to pick from a "category" of stacking.

That's just my feeling as a non-FE person.

**Comment by Fupete** [comment]
I agree. We have to try to not touch components z-index here. 
Maybe we just need to resolve our sidebar menu z-index that is the original sin.
Indeed our sidebar menu approach is not completely Bootstrap Italia native (at least not used together with sticky menus and many other stuff we have...). I think that the original `z-index: auto` (changed here https://github.com/italia/designers.italia.it/commit/859d90506fcf934bd45b704ea9ec18533aa80176) was a tentative in this direction. Maybe we can revert that fix and just solve the back-to-top in other ways @Lorenzo-Pappalardo ? 🤔
