### ISSUE TITLE
Espandere le immagini dell'header delle notizie e degli eventi fino a bordo pagina

### ISSUE THREAD

**Issue by gianvitofanelli** [italia/designers.italia.it#1081]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Ho notato che le notizie e gli eventi, a risoluzioni più elevate, hanno degli spazi laterali. È possibile pensare di espandere le immagini fino al bordo della pagina per le risoluzioni alte più comunemente utilizzate dai nostri utenti (es. io sono su un MacBook Pro abbastanza diffuso)?

### Perché

Non ho dati disponibili né ritengo sia statisticamente rilevante. È un semplice appunto di tipo estetico dovuto all'osservazione.

### Contesto

- Desktop
- Browser Arc
- Risoluzione 1512x982

### Altro

<img width="1624" alt="Screenshot 2023-11-16 at 09 52 30" src="https://github.com/italia/designers.italia.it/assets/30351061/86b0f7c8-2a33-45f6-b64d-f3f36ea845ba">

**Comment by Fupete** [comment]
No, non è possibile farle ulteriormente più grandi. Seguono l'impostazione della griglia del design system: sono fullscreen fino all'ultimo breakpoint di larghezza, xxl, il cui contenitore è al massimo 1320px di larghezza.
