### ISSUE TITLE
There is a ghost in the machine 🤖 

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#1122]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

Every time I run `npm run dev` a new `sprites.svg` is created in the wrong path.
With all the consequences of committing a ghost file every time in every PR I develop if I forget to remove it from the stage.
Has anything changed in Bootstrap Italia or in dev mode @astagi @bfabio?
Is it just a problem with my machine?

### Why

Quite annoying 😮‍💨 

### Context

Dev mode. 

### More

ps. there is a musical quote somewhere 🎧 😜  
![immagine](https://github.com/italia/designers.italia.it/assets/6736103/7eabb257-f65a-4505-81c6-f7a9125bc93a)

**Comment by astagi** [comment]
Great quote ❤️ my favorite band overall.. I'll investigate soon

**Comment by Fupete** [comment]
I believe the issue birth is one month ago. Here the other linked issue: https://github.com/italia/designers.italia.it/issues/1142
