### ISSUE TITLE
Errore nei codici colore del Design System

### ISSUE THREAD

**Issue by dschillaci** [italia/designers.italia.it#1126]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Nella pagina https://designers.italia.it/design-system/fondamenti/colori/ alcuni codici colore non corrispondono alle tonalità indicate ma sono una ripetizione delle palette superiori. 

### Perché

Mi sono accorto dell'errore mentre cercavo di reperire i codici colore hex e facendo dei test mi sono accorto che non corrispondevano al colore indicato. Vale anche per HSL e contrasto su sfondo bianco.

### Altro

FYI @zetareticoli

**Comment by zetareticoli** [comment]
Grazie @dschillaci per la segnalazione, nella PR #1139 sono stati corretti tutti.
