### ISSUE TITLE
Link sbagliato per i templates HTML

### ISSUE THREAD

**Issue by zetareticoli** [italia/designers.italia.it#1216]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Il link "Anteprime dei template HTML del sito comunale" presente nella pagina [Realizza l'interfaccia](https://designers.italia.it/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale/) ha una URL sbagliata.

### Perché

La URL sbagliata compromette la navigazione al tab "Flussi di servizio"

**Comment by Fupete** [comment]
@zetareticoli questo è fixato con la PR di stamane giusto?
