### ISSUE TITLE
Scusate: responsabile pubblicazione, me lo sono perso...

### ISSUE THREAD

**Issue by jdeyla** [italia/designers.italia.it#124]
Ciao, ho un dubbio sulla normativa e gli obblighi.
Dov'è finito l'obbligo a pubblicare il nome responsabile della pubblicazione dei contenuti di un sito?
La direttiva Brunetta (http://www.funzionepubblica.gov.it/articolo/dipartimento/26-11-2009/direttiva-n-8-2009) diceva

"Le pubbliche amministrazioni individuano uno o più responsabili del procedimento di pubblicazione di contenuti sui siti internet di propria competenza.
Tali nominativi, completi di indirizzo e-mail, devono essere raggiungibili dalla barra di coda del
relativo sito presente in tutte le pagine all'indirizzo nomesito.gov.it/responsabile."

Ma qui ad esempio http://www.funzionepubblica.gov.it/responsabile
non c'è e qui nemmeno http://www.agid.gov.it/responsabile

è stata abrogata/ superata o si è persa per strada?

Qui non ne vedo più traccia http://design-italia.readthedocs.io/it/stable/doc/service-design/normativa.html

**Comment by francescozaia** [comment]
Chiudo per inattività. Forse il [Forum](https://forum.italia.it/) è più adatto per questo tipo di domande.
