### ISSUE TITLE
Content(ds): revisione tono di voce componenti 

### ISSUE THREAD

**Issue by danielenole** [italia/designers.italia.it#1242]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Verificare i contenuti su pagina delle schede componenti, in particolare come li chiamiamo (italiano vs inglese, con vs senza maiuscola) etc

### Perché

Al momento non c'è consistenza

**Comment by Fupete** [comment]
Partially fixed by #1254 in `v1.beta.1`.
