### ISSUE TITLE
Aggiornare links a risorse per il modello ASL

### ISSUE THREAD

**Issue by zetareticoli** [italia/designers.italia.it#1276]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

È necessario aggiornare i links delle risorse disponibili per progettare l'interfaccia del modello ASL.

### Perché

Rendere accessibili le risorse pubblicate in Figma Community oppure su repository dedicato GitHub.

**Comment by Fupete** [comment]
@zetareticoli questa è già risolta? O puoi dettagliare meglio?

**Comment by zetareticoli** [comment]
@Fupete credo sia stata risolta in #1310, forse ho dimenticato di agganciare la issue alla PR
