### ISSUE TITLE
Correggere scheda Come contribuire > Per designer

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#1323]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Va riformulato il testo con le istruzioni per la community Figma, facendo riferimento alla tua copia draft, e non più al remix.

### Perché

Non esiste più la possibilità di fare "remix" nella community Figma. Hanno rimosso la funzionalità.

**Comment by Fupete** [comment]
Dovremo far riferimento a segnalare il contributo in un commento. E farlo vedere come però? Solo dopo un contatto successivo? È da fare un approfondimento cc @zetareticoli

**Comment by zetareticoli** [comment]
@Fupete  un commento alla fine non è un vero e proprio contributo, dobbiamo rimandare sempre alle issues di GitHub per segnalare cose che non vanno bene o proposte nuove.

I commenti devono essere usati per dire "grazie", "bello", "non mi piace" etc. 

Nel modello di contribuzione dei modelli di sito stiamo scrivendo:

> Per inviare i tuoi contributi dedicati alla progettazione delle interfacce dei modelli di sito e servizi:
> 1. vai al repository GitHub della risorsa e apri una segnalazione evidenziando intenzioni e possibilità del contributo proposto
> 2. scarica una copia del file dedicato da Figma Community oppure crea una copia personale (fork) del repository GitHub dedicato alla specifica risorsa
 > 3. una volta completate le modifiche, apri una richiesta di integrazione (pull request) su GitHub.

**Comment by Fupete** [comment]
Sì, leggi "segnalazione" dove ho scritto "commento" sopra. Hai ragione.

Sulla PR per i contributi di design invece bisogna approfondire il tema. Non è così lineare essendo il sorgente in Figma. 

Facciamo un approfondimento insieme appena possibile prima di aggiornare il modello di contribuzione.

D.
