### ISSUE TITLE
Upload - glitch variante drag and drop

### ISSUE THREAD

**Issue by zetareticoli** [italia/designers.italia.it#1378]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Problema di visualizzazione dell’icona.

C'è errore 404 di caricamento di una risorsa
https://designers.italia.it/dist/assets/upload-drag-drop-icon.svg

### Perché

Visualizzare l'icona correttamente.

**Comment by zetareticoli** [comment]
@Fupete @astagi ho aggiunto l'immagine mancante cambiando il path in `upload.json` come si vede in https://github.com/italia/designers.italia.it/commit/0b4daaf837049d824956e4ac286039dc91b81ebe

però nel compilato continua a cercare l'immagine nel path sbagliato, ovvero `/dist/assets/upload-drag-drop-icon.svg`

**Comment by Fupete** [comment]
In ogni caso quel json viene rigenerato partendo dalla API di BSI a ogni `npm run prepare-content`, non credo sia possibile correggerlo a mano @zetareticoli, verrebbe sovrascritto alla generazione successiva no @astagi ?

Questa issue è forse anche relativa a questa https://github.com/italia/designers.italia.it/issues/1142 probabilmente, e credo vadano risolte in ogni caso in BSI @astagi. Wdyt?

**Comment by zetareticoli** [comment]
Il problema credo sia nel path dell'immagine che non viene trovata in documentazione, perché su BSI si vede invece correttamente

**Comment by Fupete** [comment]
Chiudo questa. È legato al tema icone più generale, da risolvere lì: https://github.com/italia/designers.italia.it/issues/1142
