### ISSUE TITLE
Proposta link pagina LG per Kit test usabilità

### ISSUE THREAD

**Issue by roby986** [italia/designers.italia.it#138]
Ciao,
nella pagina https://designers.italia.it/kit/usability-test/ credo sarebbe più adeguato nella sezione "Linee Guida" inserire il link alle linee guida relative al protocollo per fare i test di usabilità (su cui è basato il kit) https://design-italia.readthedocs.io/it/stable/doc/user-research/usabilita.html#protocollo-eglu-lg-per-la-realizzazione-di-test-di-usabilita 
Che ne dite?

**Comment by francescozaia** [comment]
Se ne è parlato internamente (cc @sbronzolo)
