### ISSUE TITLE
Aggiornare le liste

### ISSUE THREAD

**Issue by zetareticoli** [italia/designers.italia.it#1458]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

In seguito all'aggiornamento del componente Lista ([Bootstrap Italia v2.11.0](https://github.com/italia/bootstrap-italia/releases/tag/v2.11.0)), è necessario verificare dove viene utilizzato e in caso modificare il markup. 

Questa issue deve essere risolta prima o insieme a #1457 

### Perché

Evitare che tutte le liste perdano la corretta formattazione-

**Comment by Fupete** [comment]
Qui la PR di feat: https://github.com/italia/designers.italia.it/pull/1463
