### ISSUE TITLE
Comportamento anomalo menu mobile nel componente Bottomnav

### ISSUE THREAD

**Issue by Giaimo-DTD** [italia/designers.italia.it#1480]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Nella pagina del componente Bottomnav https://designers.italia.it/design-system/componenti/bottomnav/, in modalità mobile, il menu a fondo pagina apre il menu di primo livello e non il menu dei componenti come invece avviene con gli altri componenti

### Perché

comportamento anomalo

**Comment by Fupete** [comment]
@Giaimo-DTD non riesco a riprodurre il bug. È ancora presente? 

Qualche giorno fa ho corretto un typo sul naming del componente, forse era dovuto a quello.

**Comment by Giaimo-DTD** [comment]
sì sembra risolto!
