### ISSUE TITLE
La documentazione del componente video player non è completa

### ISSUE THREAD

**Issue by Giaimo-DTD** [italia/designers.italia.it#1482]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Le specifiche di design risultano in stesura
src/data/content/design-system/componenti/video-player.yaml

### Perché

completare la documentazione

**Comment by Fupete** [comment]
Già presente in https://github.com/italia/designers.italia.it/issues/1421
