### ISSUE TITLE
La pagina contatti contiene dati non aggiornati

### ISSUE THREAD

**Issue by francescozaia** [italia/designers.italia.it#150]
Nella pagina [contatti](https://designers.italia.it/contatti/), l'iframe di iPress per i "Comunicati stampa" e la sezione "Eventi" non sono aggiornate da molto tempo. Che facciamo @francescomda?

**Comment by francescomda** [comment]
Secondo me togliamo entrambi @francescozaia 

iPress sicuramente, dato che lo abbiamo rimosso dal sito del Team. Per la sezione Eventi non siamo in grado di aggiornarla, e in più c'è già l'account twitter che svolge lo stesso ruolo.
