### ISSUE TITLE
[BUG] Colore del testo sbagliato. Pagina ESPLORA.

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#207]
Queste due righe di esplora.html cambiate da questa [PR](https://github.com/italia/designers.italia.it/commit/cc2a42b648f7c6fe818282037685c49d8dfbdb07#diff-f0ec610750285fef7958137c58a81151187a8210bd1da843f966aef2fe3d088cR21) hanno inserito un errore di front end nella pagina Esplora. 

**Comportamento atteso:**   
avere testo bianco (classe u-text-white) sui fondi blu. 
![immagine](https://user-images.githubusercontent.com/6736103/119528765-c5174700-bd81-11eb-894f-a1a20d359a4e.png)

**Comportamento reale:**   
testo grigio scuro. 
![immagine](https://user-images.githubusercontent.com/6736103/119528741-bfb9fc80-bd81-11eb-8dcd-8c8930f4622f.png)

Chi scrive non conosce il motivo di questa modifica che potrebbe essere stata indotta per altre cose necessarie nel sito web, da verificare prima della risoluzione. 

cc @westcoast @francescozaia

**Comment by francescozaia** [comment]
Fixed!
