### ISSUE TITLE
Use a package manager for frontend dependencies

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#246]
We should take a look at the build dependencies and update them if possible.

**Comment by bfabio** [comment]
Turns out we were using js dependency just for the build phase, which we can drop (#250).

The part we should actually take a look at is the [vendoring of frontend dependencies](https://github.com/italia/designers.italia.it/tree/master/assets/toolkit/vendor) and use package management there.

**Comment by bfabio** [comment]
This will be handled with the upcoming site refresh.

**Comment by Fupete** [comment]
Re-routing this to [next](https://github.com/orgs/italia/projects/15) project, assigned to @astagi to verify and follow up.

**Comment by bfabio** [comment]
We can close this one, it's a given since we're using Gatsby.
