### ISSUE TITLE
Next: mobile burger button doesn't work

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#394]
![immagine](https://user-images.githubusercontent.com/6736103/199034729-f2d6f96a-1455-433f-a7f0-ad842fc89bc3.png)

The mobile burger button doesn't work. Tapping the icon does nothing, instead of open the left main mobile menu.

Could be a JavaScript issue? Maybe linked to how we import in app the custom JS from the header component of Bootstrap Italia? 

cc @astagi @OscarBresolin

**Comment by gpeirolo** [comment]
Fixed in [48a2b1b](https://github.com/italia/designers.italia.it/commit/48a2b1b03f1d24ecab54f211babf6d88d2235212)
