### ISSUE TITLE
Next: highlights: numbers grid is really odd

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#396]
![desktop numbers grid](https://user-images.githubusercontent.com/6736103/199040680-f6a07394-b54e-4567-84ec-434164c98cfc.png)

![immagine](https://user-images.githubusercontent.com/6736103/199043915-dc94d84b-2916-4751-a93c-40a12314ac1e.png)

The look&feel of the whole numbers grid is really odd, each space between elements is different.

I think it is the `flex justify-content-start` applied to each separate number-icon-label block, mixed with the label `max-width` and different words length... 

How can we improve it? Or we need a different approach? 

cc @astagi @OscarBresolin

**Comment by gpeirolo** [comment]
@Fupete how about aligning the icon/number block to the right? Seems to work fine on mobile/desktop (see attached screeenshots).

![Image](https://user-images.githubusercontent.com/38532526/200297608-63689acb-12a0-487e-ad94-03dd72460598.png)
![Image](https://user-images.githubusercontent.com/38532526/200297607-df15cd2a-ecf7-4edb-8a6f-351d75ef4162.png)

**Comment by Fupete** [comment]
It could be.
The downside is that I think we will need something (line, more space, ...) to separate left and right blocks in this case ... in fact there is a possibility that the label of the right number seems connected to the first number on the left, don't you think?
In your images I also see too much space / margin / padding on the right side of the table right?

**Comment by Fupete** [comment]
Or we could go in a direction top-bottom (label top, number bottom) for each single number 🤔 ?  I tag on on the Figma file with this test... 
![testing top-bottom solution for numbers](https://user-images.githubusercontent.com/6736103/200311780-824082e5-50f0-43ec-8f58-1997082f3103.png)

**Comment by gpeirolo** [comment]
@Fupete the new version certainly seems more comprehensible and intuitive.
Nevermind the margin on my examples, I was just testing...

**Comment by gpeirolo** [comment]
@Fupete any news?

**Comment by Fupete** [comment]
Let's go in the new direction more simple top-bottom 🙏 Tx.

**Comment by gpeirolo** [comment]
Fixed in  [beba23d](https://github.com/italia/designers.italia.it/commit/beba23d4cebfcfab97448f755842ad85cce7c865)

**Comment by Fupete** [comment]
The correct number typography style-class is `display-1` and not `h2`. 

![a number and its icon](https://user-images.githubusercontent.com/6736103/200583460-cac0a25b-c407-49fc-8903-0261c8777d3e.png)


And you need to re-center vertically with the icon on the left in this case.

**Comment by Fupete** [comment]
Moved from Done to Doing 🙏

**Comment by Fupete** [comment]
Can't we vertically center icon and number? Maybe just a pt-1 or pt-2 (or mt-1, mt-2) on the icon?

**Comment by gpeirolo** [comment]
Fixed in [c3e1386](https://github.com/italia/designers.italia.it/commit/c3e138605d4c8f4f45fdf8547eff4c310f48fe8a)

Ex: https://designers-italia-it-next.vercel.app/test-components/highlight/
