### ISSUE TITLE
Next: automation: share scripts >>> cards missing

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#407]
![share dropdown](https://user-images.githubusercontent.com/6736103/199722269-933d2732-b618-4666-95bc-bad12d1764e4.png)

We need the right script for each different social network.

Maybe we could use [sharer.js](https://ellisonleao.github.io/sharer.js/) ([repo](https://github.com/ellisonleao/sharer.js))? As seen on innovation.gov.it website ([ref](https://github.com/teamdigitale/innovazione.gov.it-site/blob/main/source/javascripts/index.js#L12))

cc @astagi

**Comment by Fupete** [comment]
@bfabio I reopen this for backlog: I just noticed that the share works well on current page share. But we have the share also on bottom of each cards... in those cases we must copy/share title and url of the card itself, not the current page 🤷‍♂️

**Comment by Fupete** [comment]
To remember: tomorrow @bfabio @astagi we have to check this (last comment).

**Comment by bfabio** [comment]
@Fupete @astagi I'm going to take up this one

**Comment by Fupete** [comment]
@bfabio tx 🙏

**Comment by Fupete** [comment]
Updates:
1. we have the sharer works for pages tx to @bfabio 
2. I have temporarily disabled sharer for cards here https://github.com/italia/designers.italia.it/commit/26cec7dbecf9a3e8eaa48aa5c5d28cfa44d89d60, we will be back on this next year for milestone Beta. 

Tx again. I let this open as a post-it.
