### ISSUE TITLE
Next: meta open graph

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#410]
We need to prepare the right open meta graph approach for SEO and sharing.

cc @astagi @danielaiozzo @OscarBresolin

**Comment by Fupete** [comment]
Questions / Notes:
1. do we need to prepare a section dedicated to the open graph in the `YAML` file structure of the page?
2. do we need some automation to use other fields, which we already have elsewhere in the `YAML` file structure (example: title, description, ...) if some of the fields are left blank?

**Comment by gpeirolo** [comment]
Implemented in [3a6b483](https://github.com/italia/designers.italia.it/commit/3a6b483d9d323318ee445d0bc0057ba8ee5979ca).

1. Added `seo:` node to yaml data files for easy editing of meta properties (see `data/pages/perche/index.yaml`). 
2. Empty properties are inherited from general gatsby-config.js values which are used by defaukt
