### ISSUE TITLE
Next: responsive images

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#411]
We need to develop the best approach to deliver responsive images.

Can we use the new Gatsby plugin [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image)?

cc @OscarBresolin @westcoast @bfabio

**Comment by bfabio** [comment]
> Can we use the new Gatsby plugin [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image)?

Sure.
Also, take a look at https://github.com/teamdigitale/gatsby-site which has a base configuration with goodies like gatsby-plugin-image installed.

**Comment by astagi** [comment]
Plugin installed.

**Comment by bfabio** [comment]
@astagi note that gatsby-plugin-sharp [doesn't generate AVIF images by default](https://www.gatsbyjs.com/plugins/gatsby-plugin-image#customizing-the-default-options), so we configured it explicitly to generate them.

There's a significant improvement in quality and file size for browsers supporting them

**Comment by Fupete** [comment]
FYI @gpeirolo

**Comment by Fupete** [comment]
@gpeirolo the plugin works. Have you already planned to change every image used in your templates/components with this approach?

**Comment by gpeirolo** [comment]
@Fupete not yet. Static image are easy to optimize but dynamc images (such as the ones we pull from json) are much more complicated to implement.

**Comment by gpeirolo** [comment]
@Fupete update: @marsanwedoo has implemented the dynamic images component. Kudos to him as it was **really** complicated.
Tomorrow we will modify the other components to use it.

**Comment by Fupete** [comment]
@marsanwedoo 💙 🫐 📘 🤗 🫂 🥳 🎉

**Comment by astagi** [comment]
Kudos @marsanwedoo  🚀
