### ISSUE TITLE
Next: header/menu issues inherited by BI

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#412]
There are two issues reported on the **header nav** component of Bootstrap Italia to be addressed: 

- https://github.com/italia/bootstrap-italia/issues/755
- https://github.com/italia/bootstrap-italia/issues/756

cc @astagi @OscarBresolin

**Comment by gpeirolo** [comment]
Pushed PR#767 that fixes the first issue

**Comment by Fupete** [comment]
Seen https://github.com/italia/bootstrap-italia/pull/767, reviewed and approved. We can merge it @astagi .

**Comment by gpeirolo** [comment]
Pushed [PR#768](https://github.com/italia/bootstrap-italia/pull/768) that fixes the second issue

**Comment by Fupete** [comment]
I see the PR on BI are fixed. So, can we close this @gpeirolo ?

**Comment by gpeirolo** [comment]
@Fupete I would wait until I have updated the BI module with the new released version of BI (2.0.9?) .

**Comment by Fupete** [comment]
That's correct. Tx. FYI @astagi

**Comment by gpeirolo** [comment]
Fixed in https://github.com/italia/designers.italia.it/commit/2967b743fc03d96b22a5309af7014f258dfe3e5b
