### ISSUE TITLE
Next: file structure review

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#413]
We need to review the current/best file structure for:
- data content `yaml`s for pages, posts and cover archives at any levels ...
- templates `js`s for the 4+ levels to be used for pages and the special ones for different kind of posts and archives ...

cc @astagi @OscarBresolin

**Comment by Fupete** [comment]
Question eg. about pages: — from what I understand of the current file structure, I may have mistaken 🤔 — we need a single `js` file for each page` pages/perche/perche.js` + `data/pages/perche/perche.yaml`. Can we only have 4 `js` general templates (one for each website pages depth level) and then simply refer to them from the individual `yaml`s? Or can the right `js` template 1, 2, 3, 4+ be recalled automatically identified by the depth level of the folder where the content `yaml` is?

If not we risk a lot of duplicated `js`s for each level no? ♾

**Comment by gpeirolo** [comment]
@Fupete you are correct that is the current approach and also the default modus operandi of Gatsby.
It's possible to create pages programmatically but I suppose this is more suitable for detail pages (eg: news, events, etc.):
https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/
https://www.gatsbyjs.com/docs/programmatically-create-pages-from-data/

Analyzing the latest version of the UI in Figma we saw that level 2/3/4 pages are not consistent in their use of block of contents.
Some pages have more than one editorial section (no problem in that, our component can be looped) but sometimes a card highlight appears between them or right at the end and this cannot be done without implementing per-page module import and order.

We may need to organize a meeting to solve this.
Feel free to invite me and @OscarBresolin (not tomorrow 10/11).

**Comment by gpeirolo** [comment]
Pushed the file structure we agreed upon in [62af3a8](https://github.com/italia/designers.italia.it/commit/62af3a89cc999870b06579f50e7281234bb808fb)

All template levels (1 to 4) are implemented.

Merged in `next`

**Comment by Fupete** [comment]
@gpeirolo seems perfect. 

A question: path root is relative to where is the current-page.js. So, to link to a child-page-x, we need to use a url like `current-page/child-page-x`, also on the `current-page` page. Is it?

**Comment by gpeirolo** [comment]
@Fupete I just pushed a small fix for the ourl paths in our data  [a8ff86d](https://github.com/italia/designers.italia.it/commit/a8ff86d9e8bbdec25099b6c8b11dd33967d1ae94)

It's better to add a slash at the end of each link (at least if the page has childs) so that it's easier to link to a child page. Eg:
Old: level1/level2/level3
New: level3/
