### ISSUE TITLE
Next: simplify Share dropdowns yaml datas

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#418]
In order to simplify all the `yaml` page files, I think we can abstract (move) all the Share dropdowns groups of datas (page Share dropdown, but also each card ones, they are all the same) to just one dedicated `yaml` component level setup file `share.yaml`, or plain `setup.yaml` maybe, in the data folder. Is it not?

cc @astagi @OscarBresolin

**Comment by Fupete** [comment]
Linked to #413 and #407

**Comment by gpeirolo** [comment]
I agree. `share.yaml` inside `data `folder seems the best approach to me.

**Comment by gpeirolo** [comment]
Fixed here [f152c3b](https://github.com/italia/designers.italia.it/commit/f152c3b74a8fe9db207dcf66fc66b4b04408b77a)

**Comment by Fupete** [comment]
Have you already merged on the `next` branch?

**Comment by gpeirolo** [comment]
No, I'm about to do it together with the 301 redirects plugin.

**Comment by gpeirolo** [comment]
@Fupete merged in next
