### ISSUE TITLE
Next: Bootstrap Italia js dependencies/treeshaking issues-question

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#419]
Update: as said by @gpeirolo: It's probably necessary to fix Bootstrap Italia first and then update it in the DI repo, also updating the way we activate the js components. ref: https://github.com/italia/designers.italia.it/issues/419#issuecomment-1315046550

——

Original issue: 

![immagine](https://user-images.githubusercontent.com/6736103/201083770-97d3927f-44c4-4725-bfbc-3231cfd1de68.png)

All input field labels (modal feedback ref.) don't move over the field as planned during editing .. is it yet the same problem we had with Bootstrap Italia javascript dependency a few days ago @astagi @marsanwedoo?

cc @OscarBresolin

**Comment by gpeirolo** [comment]
@Fupete i would advise to close this issue and open a generic "Bootstrap Italia js dependencies/treeshaking issues" with @astagi and @marsanwedoo as Assignees and me as a watcher.

It's probably necessary to fix Bootstrap Italia first and then update it in the DI repo, also updating the way we activate the js components.

**Comment by Fupete** [comment]
@gpeirolo I just updated this issue title and description and re-assigned to @astagi and @marsanwedoo. Status moved to "TO DO".

**Comment by Fupete** [comment]
@astagi do we need a twin issue on Bootstrap Italia too?

**Comment by astagi** [comment]
@gpeirolo @Fupete for reference https://github.com/italia/bootstrap-italia/issues/729

**Comment by Fupete** [comment]
@gpeirolo everything ok?

**Comment by gpeirolo** [comment]
@marsanwedoo is working on a fix for the labels in the BI repo.
