### ISSUE TITLE
Next: 301 redirects ready

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#420]
Are we ready with the tools for that @gpeirolo ? 
Do we need to test something @astagi ?

cc @OscarBresolin

**Comment by gpeirolo** [comment]
Merged in next (commit [08b76e5](https://github.com/italia/designers.italia.it/commit/08b76e5d87cac1216534ca4814b928ec65c7917f))

**Comment by Fupete** [comment]
How does it work?

**Comment by gpeirolo** [comment]
Basically it creates a complete htacces file for apache.

Redirects have to be written in the gatsby-config.js file below the 
`// redirects go here`
comment.

Plugin docs for other configs (they should be tested) are here:
https://www.npmjs.com/package/gatsby-plugin-htaccess

**Comment by Fupete** [comment]
@gpeirolo Do we need to test it in production before closing this? cc @astagi

**Comment by gpeirolo** [comment]
@Fupete I think it would be better.

**Comment by gpeirolo** [comment]
@Fupete I have temporarily disabled the plugin (by just commenting the setup in `gatsby-config.js`) as it makes no sense in a staging environment.

**Comment by Fupete** [comment]
@gpeirolo @astagi (cc @bfabio) this plugin can't work. It's for Apache. We need something similar to the one we use on the current designer's website, that uses a client-side approach.

**Comment by gpeirolo** [comment]
@Fupete Client-side only approach is not SEO friendly though.
More about this:
https://www.gatsbyjs.com/plugins/gatsby-redirect-from/
https://kremalicious.com/gatsby-redirect-from/#server-side-redirects

**Comment by Fupete** [comment]
Using GitHub pages (and Vercel also) we really don't have the server-side alternative 🤷 as far as we know. 

Maybe we can automate the process (right as the current website) during the next createPages approach (with @astagi) using slug metadata aliases in each page contentyaml, and reading during the building to generate the right 301 index.html in the right (fake) folders.

**Comment by gpeirolo** [comment]
There'a Vercel plugin to generate redirects:
https://github.com/universse/gatsby-plugin-zeit-now

**Comment by Fupete** [comment]
@bfabio @astagi interesting to read also the official Gatsby config method here https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect (that links also a meta plugin for static situations like our github pages i think, just in case)

**Comment by bfabio** [comment]
> @bfabio @astagi interesting to read also the official Gatsby config method here https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect (that links also a meta plugin for static situations like our github pages i think, just in case)

That's the right approach, abstracting the redirect with [`createRedirect()`](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect) and then installing the plugin implementing it, in our case [`gatsby-plugin-meta-redirect`](https://www.gatsbyjs.com/plugins/gatsby-plugin-meta-redirect/)

**Comment by bfabio** [comment]
Depends on #628.

**Comment by bfabio** [comment]
`gatsby-plugin-meta-redirect`'s repo is archived but should have all the features we need, but if it turns out that's not the case we might need to fork it.

**Comment by Fupete** [comment]
👌 @bfabio, I also found this plugin: `gatsby-redirect-from` (https://www.gatsbyjs.com/plugins/gatsby-redirect-from/) to use in combination with it, it looks promising.

**Comment by bfabio** [comment]
@Fupete `gatsby-redirect-from` is not exactly what we need, but it's on the same layer:

```
+-----------------------------+
|                             |
| Glue between source content |            We have a custom content format
| format and createRedirect() | +------>   so we have to implement our glue
|   fe. gatsby-redirect-from  |
+-----------------------------+
|                             |
|   Gatsby's createRedirect() |
|                             |
+-----------------------------+
|                             |
| Plugins implementing the    | +------>   gatsby-plugin-meta-redirect
| redirs with whatever method |            does everthing we need here
|                             |
+-----------------------------+

```

**Comment by bfabio** [comment]
Fixed in https://github.com/italia/designers.italia.it/pull/635.
