### ISSUE TITLE
Next: create/prepare all content files

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#421]
Create/prepare all files (`js` and `yaml`) and folders for all pages and posts, following the new information architecture.

cc @astagi @OscarBresolin @danielaiozzo

**Comment by Fupete** [comment]
Memo: priority to `light` for just another week.

**Comment by gpeirolo** [comment]
@fupete I just pushed the new community template and the "Community" page with the content taken from Figma.
"Progetto" page updated as well.

**Comment by gpeirolo** [comment]
@Fupete added the "Article detail" page:
https://designers-italia-it-next.vercel.app/level1/level2/article-detail/

There was no need to use another template, the one from level3 was suitable.
