### ISSUE TITLE
Next: automation: feedback backend

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#423]
We have to develop the "meta-backend" of the page feedback component.

We will use a form to mail approach. 

cc @gpeirolo

**Comment by Fupete** [comment]
Memos: 
- do a new a11y review of the current markup and pattern
- this is partly connected to newsletter subscription, still to confirm, see the ux

**Comment by Fupete** [comment]
We need a meet early days of next week @gpeirolo @astagi

**Comment by bfabio** [comment]
Steps

- [ ] Adapt the API code
- [ ] Configure Mailgun
- [ ] Setup the API on Vercel 
  - [ ]  Setup a subdomain for the backend API (https://github.com/italia/designers.italia.it/issues/435)
    - [ ] Add DNS record
    - [ ] Create and configure a reCAPTCHA for the domain
- [ ] Create recipient email address / group
- [ ] Cleanup and set production values (fe. actual email address)

**Comment by bfabio** [comment]
@Fupete we probably need an issue for the frontend integration, unless we want to track everything here

**Comment by Fupete** [comment]
@bfabio correct, I open it. I also just correct a minor a11y issue with the feedback front end here https://github.com/italia/designers.italia.it/pull/467, waiting for the review to merge in `next`

**Comment by bfabio** [comment]
@Fupete we should also discuss whether we need a way to tell users apart in feedback messages or not (we most probably do)
