### ISSUE TITLE
Next: validator error: stray start tag 

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#426]
There is a "feedback.js" script stray start tag outsideof `<head>` or `<body>` sections.

![source w3c validator](https://user-images.githubusercontent.com/6736103/201618703-3014950b-9e97-4b4b-b179-f72416f0d1dc.png)

cc @astagi @OscarBresolin

**Comment by gpeirolo** [comment]
@Fupete I think it's just the js for the floating Vercel comments (the host is vercel.live). We have no control over it but there's no problem since it will not be deployed in production.

**Comment by Fupete** [comment]
That was fast: okay, correct, better, false alarm ⏩ 👍
