### ISSUE TITLE
Next: paragraph line-height

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#427]
The `p` paragraphs should have Bootstrap Italy's [default line height](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/tipografia/#paragrafi), so: check for custom values, and delete them if needed. 

ps. yeah, previous mockups on Figma had a value 👎 , luckily for desktop resolutions only (18/**24** instead of the correct 18/**28**), due to a UI kit issue, fixed with the [latest release](https://twitter.com/Fupete/status/1589998900827803652) v3.0.0-beta.1.

cc @astagi @OscarBresolin

**Comment by gpeirolo** [comment]
Fixed in [6fac4f8](https://github.com/italia/designers.italia.it/commit/6fac4f818408205678b2ba548abbbba4acce11fd).
Merged in `next`.
