### ISSUE TITLE
Next: shift to "createPage" approach and define/start code refactoring...

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#428]
**Update:**

this became a meta-issue to track our progress to shift to a "createPage" approach, using the full potential of Gatsby. Owner will be @astagi . 

—

Original issue: 
We need to develop the correct development approach for the 4 post-types with archives [notizie, eventi, media, articoli di approfondimento] in order to:
- templating - shared unique tmpl-X.js per type
- archives - generate list of posts (correct cards, with dinamic data), with pagination [graphql?]
Question: the same "archives approach" will be useful for the "tag content archives" too?

cc @marsanwedoo @OscarBresolin

**Comment by gpeirolo** [comment]
@Fupete @astagi This might be the plugin we need to parse multiple `.yaml `files and build an array out of them:
https://www.gatsbyjs.com/plugins/gatsby-transformer-yaml/

Here's an approach (in this case with md files) that might work for us:
https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/gatsby-node.js   (from line 16 on)

**Comment by Fupete** [comment]
Preliminaries done @astagi : just added [here](https://github.com/italia/designers.italia.it/commit/8aa04aaddcd857eeedad7025e651e36a4cc94bf8) ✅ all the right template names to the `YAML` files.

**Comment by Fupete** [comment]
Note: we imagine a folder structure like this: 

- src/
  - pages/
    - just all the yamls with all the directory structure needed
  - templates/
    - all the templates here, eg. level1.js will be here, together with its template tmpl-level-1.js. 
  

ps. we need to add templates for 404 and some other minor pages. 
pps. pay attention that same levels (design-system ones mostly) doesn't have name consistency at the moment, I can guide you.

**Comment by Fupete** [comment]
Note: we can use this approach also to get BI `json` components during page creation.
