### ISSUE TITLE
Next: subdomain to test

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#435]
We need to explore the possibility to activate a subdomain like `prossima.designers.italia.it` that point to the branch `next` build. To use it like a demo/preview. 

cc @bfabio @astagi

**Comment by bfabio** [comment]
@Fupete isn't https://designers-italia-it-next.vercel.app enough for demos?

**Comment by Fupete** [comment]
@bfabio perfect. Tx. 

Info: we are planning, for the future milestone A, to launch on a secondary domain, where we can do usability tests and collect page feedback from the public/users, for a limited time before the official launch. This pre-launch, which will be public anyway, would certainly benefit from an official domain, not a Vercel one.

cc @pedromaria88

**Comment by bfabio** [comment]
This is useful for #435 as well.

Is prossima.designers.italia.it the final domain? Can we go ahead with it @Fupete?

**Comment by bfabio** [comment]
On a second thought, we'll need a non-temporary subdomain once the backend is in production and `prossima.d.i.i` won't do.

We need a `feedback.designers.italia.it`.

**Comment by Fupete** [comment]
@bfabio we can go ahead with the "prossima" domain and deploy approach we discussed 🙏 ⭐

**Comment by bfabio** [comment]
Done.
