### ISSUE TITLE
Next: building issue with svg/images + question

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#444]
There is a 🟡 warning for each SVG image during building. 
Is it related to our new image plugin @marsanwedoo @gpeirolo? 

![building log item screenshot](https://user-images.githubusercontent.com/6736103/203537347-6833db9f-5367-40cc-81ca-ea522af2c416.png)

Question: do we need to check if the image plugin act as expected? (responsive, lazy loading, the image outside viewport behavior, etc.)

cc @astagi @bfabio @OscarBresolin

**Comment by gpeirolo** [comment]
Pushed the fix in `next`.

The plugin sem sto be workin but please do an indipendent check @Fupete @astagi @bfabio

**Comment by Fupete** [comment]
We will do tx, I let this issue open just to remember ( cc @bfabio )

**Comment by Fupete** [comment]
Maybe is it related to the new issue https://github.com/italia/designers.italia.it/issues/466 🤔 @bfabio @marsanwedoo?
