### ISSUE TITLE
Next: sticky menu and sidebar doesn't work in production/Vercel

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#449]
As the subject, everything works fine in local dev ambient — the main sticky menu at scroll, and sticky design system sidebar at the scroll, work just super smooth and delicate — but they don't work on production/Vercel ⚠️ 🔴 

See this original comment https://github.com/italia/designers.italia.it/pull/438#issuecomment-1325364640 by @gpeirolo for the new design system template. Maybe it is the same issue referred to here https://github.com/italia/designers.italia.it/issues/419

cc @gpeirolo @OscarBresolin

**Comment by Fupete** [comment]
@gpeirolo May I close this too?

**Comment by gpeirolo** [comment]
@Fupete The sticky menu seems to be working now:
https://designers-italia-it-next.vercel.app/level1/fondamenti/

I would close it.
