### ISSUE TITLE
Next: integrate feedback automation to front end

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#469]
As referred by https://github.com/italia/designers.italia.it/issues/423 we need to integrate into the front end the right calls to the new form-to-mail mechanism implemented by @bfabio here https://github.com/italia/feedback.designers.italia.it

cc @gpeirolo @astagi

**Comment by bfabio** [comment]
Fixed by https://github.com/italia/designers.italia.it/pull/547. GitHub didn't close this automatically for some reason.
