### ISSUE TITLE
Pagina Siti Web PA: nuove regole di segnalazione

### ISSUE THREAD

**Issue by matteodesanti** [italia/designers.italia.it#47]
È necessario allineare quanto troviamo qua
https://designers.italia.it/progetti/siti-web-pa/
con la nuova logica di segnalazione di progetti proposta nel forum
qui https://forum.italia.it/t/come-raccontarci-il-tuo-progetto/680
compreso relativo link.

**Comment by Tabbi7** [comment]
Si possono avere informazioni ulteriori sul da farsi? Non riusciamo a comprendere nello specifico quali sono le modifiche richieste.

**Comment by matteodesanti** [comment]
SI tratta di includere anche in questa pagina le info che abbiamo inserito nel post sul forum.
Dovremo creare un layout per le schede dei vari siti, che comprendano questi elementi

**Comment by francescozaia** [comment]
La pagina sarà rimossa a breve, ad ogni modo questa richiesta non è più valida.
