### ISSUE TITLE
Next: :focus behaviour bug

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#477]
We need to check the pseudo-class class `:focus` behavior. 
The focus rectangle appears also on mouse click/touch ⚠️ , see 📷

![issue example](https://user-images.githubusercontent.com/6736103/204100006-f64ee26c-e577-4333-88a2-01818629a0dd.png)

On Bootstrap Italia 1.x this issue was resolved by this PR https://github.com/italia/bootstrap-italia/pull/595 by @OscarBresolin almost one year ago 🎈(I don't know how it's working in BI 2) 

Is it the same 🧐 tree-shaking/Gatsby js issue? @marsanwedoo @astagi ?

**Comment by gpeirolo** [comment]
@Fupete created PR
