### ISSUE TITLE
Nuovo stile designers.italia.it

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/designers.italia.it#48]
Ciao, ho visto oggi la nuova grafica della pagina https://designers.italia.it/
La mia attenzione si è immediatamente focalizzata sulla scelta del colore azzurro/acqua come sfondo o testo. Il contrasto di questo colore con il bianco non arriva nemmeno al livello AA di accessibilità. Infatti lo trovo di difficile lettura (persino fastidioso) io che non ho deficit visivo.
Non capisco il motivo di tale scelta ma suggerisco di modificarlo.

**Comment by NamanZelawat** [comment]
I would like to work on it can you suggest the change in colors more specifically.
