### ISSUE TITLE
Next: warnings [locatorjs] [locator-js] in production (Vercel)

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#498]
There are 🟡 warnings on the console about [locatorjs] and [locator-js] in production. See the image below. 

Is it something we have to be worried about? 

![warnings](https://user-images.githubusercontent.com/6736103/205086572-91d3dcba-52b2-4b79-b564-27578bc7fb01.png)

cc @astagi

**Comment by gpeirolo** [comment]
@Fupete I don't see it on my browser, could it be an estension you have installed?
https://www.locatorjs.com/

Could you try with another browser?
