### ISSUE TITLE
Next: design system sidebar remain open after navigation

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#525]
As subject. 

Right now when you navigate through the sidebar it restart with every section closed. It must retain the current section open, like in the Bootstrap Italia documentation for example.

**Comment by Fupete** [comment]
@gpeirolo any ideas why it happens only on "Componente" right now? Any settings we need to pass to the sidebar?

**Comment by gpeirolo** [comment]
@Fupete the NavSidebar component checks if the page seo name matches with the menu label and if true opens the parent accordion:

Lines 46-49
```
  if (subItem.label === page) {
    expandSublinks = true
    linksStyle = linksStyle+' contains-active'
  }
```

If you change the `seo.name` value in fondamento.yaml to match the label (eg: Fondamento) the accordion should open.
If this approach is not suitable I think we could give a `opened `parameter to the accordions.

**Comment by Fupete** [comment]
Tx. Crystal clear.

**Comment by gpeirolo** [comment]
@Fupete note that I added a meta property to the yamls in this PR:
https://github.com/italia/designers.italia.it/pull/561

metadata.activeLabel

Maybe it could be used for the same purpose in the sidebar, in the place of the seo.name

**Comment by Fupete** [comment]
@gpeirolo Tx. However soon the DS menu generation will be "automated" (hopefully), so I think `seo.name` logic is sufficient for this first release.
