### ISSUE TITLE
Next: z-index issue on mobile

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#527]
Toast message and back to top button remain under the bottom Design system sticky navigation.

**Comment by Lorenzo-Pappalardo** [comment]
Hi, can you provide more details on how to reproduce the bug?
Also, I have noticed that the arrow is off-centre. It is very easy to fix the position by applying a few css rules and disabling some of the already present.

**Comment by Fupete** [comment]
Hi @Lorenzo-Pappalardo, 

the bug is related to the "Design System" section, where there is a side menu. It happens on mobile. For example this page https://prossima.designers.italia.it/design-system/come-iniziare/per-designer/ on mobile (see image). 

![bug](https://user-images.githubusercontent.com/6736103/219618528-bf57ee63-8ac1-49e6-b0b9-778e55f5aeff.png)

We have yet to verify whether this is a bug of [Bootstrap Italia](https://github.com/italia/bootstrap-italia) or by us.

Any PR is more than welcome!

cc @astagi

**Comment by Fupete** [comment]
More: there is the same problem with the toast message (as subject): for example here https://prossima.designers.italia.it/design-system/componenti/accordion/ if you click the "copy" icon bottom of the component preview... the toast message appears (on mobile) under the bottom menu "Navigazione Design System". See image. 

![bug](https://user-images.githubusercontent.com/6736103/219620472-d7bb5d15-0f27-460e-801d-097469c519b9.png)

**Comment by Lorenzo-Pappalardo** [comment]
Hi @Fupete,
first of all thanks for the clarification.

I have analysed the problem and it seems like the solution indeed requires changing the z-index, but not only that.
In fact, fixing that actually causes another problem to show up: the "back to top" button is still on top even when the expanding the menu by clicking on the bottom navbar.
I'm attaching a screenshot of what I mean:
![image](https://user-images.githubusercontent.com/56509174/221035053-9fd00d1a-e704-41e3-80cc-730417584680.png)

Fixing this behaviour requires a change in the way the template is organized, therefore I'll need more time to come up with a solution.

**Comment by Fupete** [comment]
Thank you very much, @Lorenzo-Pappalardo for the inquiry and PR. 
We will look into the matter as soon as possible (cc @bfabio @astagi).

**Comment by Lorenzo-Pappalardo** [comment]
@Fupete 
I have found a solution which seems, at least to me, to fix all the stacking problems above and ensure the desired behaviour.
I have updated the PR with the new changes.
Let me know what you think 😄

**Comment by Fupete** [comment]
Thanks Lorenzo! 💙 

FYI @astagi 👆: maybe we need to use this fix on Bootstrap Italia?

**Comment by astagi** [comment]
Thank you @Lorenzo-Pappalardo 🙌
