### ISSUE TITLE
Next: content: review and adds

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#539]
We need to review all the titles and text. And to add what we don't have. 

To-do lists (in progress in comments to this, by me, @danielaiozzo, and @MCAlker ):

- [ ] [Home](https://prossima.designers.italia.it) (📝 review)
- [ ] [Community](https://prossima.designers.italia.it/community/) (📝 review)
- [ ] [Design system](https://prossima.designers.italia.it/design-system/), [fondamenti](https://prossima.designers.italia.it/design-system/fondamenti/), [componenti](https://prossima.designers.italia.it/design-system/componenti/) (🆕 new)
- [ ] ...

**Comment by MCAlker** [comment]
This [file](https://docs.google.com/spreadsheets/d/1fmeMu_xj94XVGVHx4etyuuvtfwBLfvKNZIJaVVnXPyA/edit#gid=0) keeps track of issues, bugs and future changes. You can filter by priority to check the most important before monday. @Fupete @danielaiozzo
