### ISSUE TITLE
Next: a11y: Tab issue with keyboard interactions

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#571]
This issue has been extracted from  our a11y review with Fabrizio here https://github.com/italia/designers.italia.it/issues/564:

We need to correct the keyboard interactions of the tab component. This is a Bootstrap Italia issue. We need to implement the correct aria-pattern for keyboard interaction. 

@astagi this is a major issue in BI as well, added an issue here to discuss and track solutions https://github.com/italia/bootstrap-italia/issues/789

**Comment by Fupete** [comment]
Fixed resolution to milestone beta @astagi, considering that it is, quite time-consuming, a fix to Bootstrap Italia. The sooner the better of course.

**Comment by Fupete** [comment]
@astagi I see that the issue https://github.com/italia/bootstrap-italia/issues/789 on Bootstrap italia is closed. Is it solved?
Can we develop the new solution, with the correct aria-pattern for keyboard interaction, here on prossima?

**Comment by astagi** [comment]
We can mark it as solved
