### ISSUE TITLE
Typography question

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#606]
IMO the typography of the current site is more pleasing than next's, I think mainly because of the shorter lines, the font and the slightly muted black.

|Before|After|
|---|---|
|https://designers.italia.it/notizie/benvenuto-kit-privacy/ ![image](https://user-images.githubusercontent.com/788293/208643027-88ec2309-110c-4e22-a793-1d1b67a64ba7.png)|https://prossima.designers.italia.it/community/notizie/20221020-benvenuto-kit-privacy/ ![image](https://user-images.githubusercontent.com/788293/208667674-aff18584-c8ec-4873-bafa-c5d29fcaabca.png)|

**Comment by Fupete** [comment]
Spring cleaning: closing this issue @bfabio for stale and publishing of `next` in the meantime.

**Comment by bfabio** [comment]
@Fupete I don't think this should be closed, the issue still stands. Of course it's not `prossima.d.i.i` anymore, but the comparison is between the published site and the old site.

**Comment by Fupete** [comment]
I think that this could be misleading. The new website follow the design system approach we design and promote.   

Maybe could be more usefull to open the discussion about this opinion to open a new issue — referring this maybe — about the design system typography approach. Don't you agree?
