### ISSUE TITLE
Next: menu mobile/sticky scroll issue

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#610]
See attached video. There is an issue browsing via sticky menu on mobile, when you are down the page you open other pages at the same scroll position..., **we must verify ASAP on desktop and other browsers too.**

Browser: Firefox Ipad.

cc @astagi 

https://user-images.githubusercontent.com/6736103/208761670-d7feb2a8-4b25-4f0f-87dc-4ab60d8f9ffc.MOV

**Comment by astagi** [comment]
Thanks @marsanwedoo!
