### ISSUE TITLE
Redirect da designer.italia.it

### ISSUE THREAD

**Issue by alexrj** [italia/designers.italia.it#62]
L'indirizzo https://designer.italia.it (senza "s") è configurato come alias di https://designers.italia.it (con la "s") invece che come redirect. All'apertura del sito appare un errore del certificato SSL perché l'hostname non corrisponde.
Andrebbe configurato come redirect, come già avviene per https://developer.italia.it/

**Comment by gvarisco** [comment]
nice catch. Should be fixed now: https://designer.italia.it
