### ISSUE TITLE
Next: redirect from prossima.designers.italia.it to designers.italia.it

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#653]
We need to prepare Vercel to redirect each `https://prossima.designers.italia.it/page/` to `https://designers.italia.it/page/`.

Note: probably we need a new repo `italia/prossima.designers.italia.it` with this scope.

**Comment by bfabio** [comment]
Just had a showerthought with a better solution: w can point the Vercel deployment for `prossima.d.i.i` to `main` and have a small banner visible only if the domain is not `designers.italia.it` that invites users to go to the actual site.

This way we don't need to:
* Create a new repo, and all the tasks it implies (set up permissions, keep them in sync with the designers.i.i repo, document it, setup the Vercel project, eventually decommission it, etc.)
* Code the redir thing

And having a banner also gets us a way to inform the user about when the `prossima.d.i.i` domain will no longer work.

**Comment by Fupete** [comment]
@danielaiozzo can you help us?

**Comment by danielaiozzo** [comment]
sure
