### ISSUE TITLE
Bug: z-index

### ISSUE THREAD

**Issue by gianvitofanelli** [italia/designers.italia.it#689]
HI,
in the [Fondamenti page](https://prossima.designers.italia.it/design-system/fondamenti/) of the design system, I noticed that the image in the header overlaps the element showing the navigation at the top. I think it's a z-index problem.

<img width="1060" alt="Screenshot 2023-03-16 at 11 28 05" src="https://user-images.githubusercontent.com/30351061/225589456-7ec05263-a74c-4b49-b064-f62955efed6f.png">

**Comment by Fupete** [comment]
It seems related to sticky header behavior. We will investigate further. Moved to the next milestone as a minor. cc @astagi
