### ISSUE TITLE
Image consistency

### ISSUE THREAD

**Issue by pedromaria88** [italia/designers.italia.it#690]
The image in the megamenu should have consistent treatment, imho

![Schermata 2023-03-16 alle 18 23 43](https://user-images.githubusercontent.com/15200891/225701944-96a68284-c5eb-4e5e-b95c-fa52b98225b2.png)
![Schermata 2023-03-16 alle 18 23 39](https://user-images.githubusercontent.com/15200891/225701953-a2a8ac6e-1c09-4ff7-9250-243b0196917d.png)
![Schermata 2023-03-16 alle 18 23 34](https://user-images.githubusercontent.com/15200891/225701959-a6d872ae-5c5a-48ec-b275-a4aa5b1308dd.png)

**Comment by Fupete** [comment]
Linked to #540
