### ISSUE TITLE
Next: a11y megamenu

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#691]
We need to consider "underlining" all links in the megamenu, although it may not be necessary to respond to WCAG. 

Source: an informal test by a user with low vision. The feedback sounds like "I can't determine if these menu items are clickable if I can't see the entire context, not everything is clickable (eg. section description)."

![context](https://user-images.githubusercontent.com/6736103/225903029-a27dd804-cac8-4fbc-b9e7-2603c4eb1ed8.png)

**Comment by cfabry** [comment]
Il SC 1.4.1 richiede che i link non debbano essere riconoscibili solo dal colore. In molti menu i link si riconoscono perché prendono la forma di "menu" in base al design, pertanto la funzionalità non è ambigua. Tuttavia in questo megamenu i link sono semplici testi; dal contesto, soprattutto con forti ingrandimenti, si potrebbero non distinguere gli oggetti selezionabili da quelli non selezionabili, pertanto la segnalazione mi sembra corretta.

**Comment by Fupete** [comment]
Update: we choose to "enhance links" with a left chevron icon and few minor adj around for a first enhancement.
