### ISSUE TITLE
Sostituzione email info@agid da privacy policy

### ISSUE THREAD

**Issue by danielaiozzo** [italia/designers.italia.it#88]
Ciao, poichè la mail info@agid.gov.it sta per essere disabilitata, andrebbe sostitutita con protocollo@pec.agid.gov.it in questa pagina https://designers.italia.it/privacy-policy/ 

Thanks!

**Comment by francescozaia** [comment]
Sistemata sul branch *redesign* in coda per la prossima release

**Comment by danielaiozzo** [comment]
Grazie mille Francesco :)

Il 28/Feb/2018 19:14, "Francesco Zaia" <notifications@github.com> ha
scritto:

**Comment by francescozaia** [comment]
Abbiamo sostituito ogni occorrenza di info@agid.gov.it con protocollo@pec.agid.gov.it, sia nella pagina [Privacy Policy](https://designers.italia.it/privacy-policy/) che in [Note Legali](https://designers.italia.it/note-legali/).

**Comment by danielaiozzo** [comment]
perfetto grazie :)

2018-03-13 12:23 GMT+01:00 Francesco Zaia <notifications@github.com>:
