### ISSUE TITLE
Regression: the viewport doesn't retain the scroll position when going back

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#890]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

(test to replicate #883 with the new form)

### Cosa

When you click on something and then go back with the back button, you go to the top of the previous page instead of the position you clicked on:

[Screencast from 2023-09-22 11-34-55.webm](https://github.com/italia/designers.italia.it/assets/788293/1735b8b5-4d96-4374-a5c2-e129ac65dee8)

This is a big regression

### Perché

Because it's a bug.

(@Fupete @danielaiozzo this section should probably be optional, it's kinda awkward for bugs)

### Contesto

Reproducible on:

* GNU/Linux
  * Firefox, 117
  * Chromium 117
  
* Windows 10
  * Chrome 117

**Comment by Fupete** [comment]
This? https://github.com/italia/designers.italia.it/issues/883

**Comment by bfabio** [comment]
Opened as a test duplicate of #883
