### ISSUE TITLE
form.agid.gov.it - Errore funzionalità "Richiesta chiave di accesso"

### ISSUE THREAD

**Issue by Gianni-Luca** [italia/designers.italia.it#909]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

Ciao, il form.agid.gov.it/ attualmente da errore (pagina bianca) quando si clicca per richiedere la chiave di accesso. 

### Perché

E' rilevante ai fini di compilazione della dichiarazione di accessibilità

**Comment by Fupete** [comment]
Ciao @Gianni-Luca, 

questo modulo serve ad aprire segnalazioni e proposte per il sito [Designers Italia](https://designers.italia.it) e per la documentazione del [design system del Paese](https://designers.italia.it/design-system) come parte del suo [modello di contribuzione](https://designers.italia.it/design-system/come-contribuire/modello-di-contribuzione/). 

Per segnalare malfunzionamenti del sito https://form.agid.gov.it ti invito a farlo direttamente con AGID, [qui trovi i loro contatti generali](https://www.agid.gov.it/it/agenzia/chi-siamo/contatti)

**Comment by pdavide** [comment]
@Gianni-Luca per problematiche relative alla compilazione delle dichiarazioni di accessibilità, è disponibile la casella email accessibilita@agid.gov.it.
