### ISSUE TITLE
Color contrast ratio in /design-system/componenti page

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#923]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

Lighthouse reports an a11y error in the color contrast at https://designers.italia.it/design-system/componenti/

![image](https://github.com/italia/designers.italia.it/assets/788293/19199785-32bc-4747-8056-c1120fad4947)

### Why

It doesn't pass WCAG AA for small text, which is the case here

https://dequeuniversity.com/rules/axe/4.4/color-contrast

![image](https://github.com/italia/designers.italia.it/assets/788293/dbb43868-13f0-479a-8b1c-c9fe9130717a)

**Comment by Fupete** [comment]
Yes. We know it. It depends on one of the last commit in Bootstrap Italia that changed color variables and classes.
We are thinking to add a class "muted-bg" there in Bootstrap Italia, and we will have to use it here instead of our current neutral-2-bg. 

cc @zetareticoli @astagi

**Comment by bfabio** [comment]
@Fupete do we have an issue in bootstrap-italia we can reference here?

**Comment by Fupete** [comment]
Fixed by https://github.com/italia/designers.italia.it/pull/1136
