### ISSUE TITLE
Scheda come iniziare Per designer: stesura contenuti e review

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#937]

**Comment by ValentinoDesigner** [comment]
http://www.imxprs.com/free/kybertech/italia_designers

**Comment by ValentinoDesigner** [comment]
Ho anche il codice come lo carico?

**Comment by Fupete** [comment]
Ciao @ValentinoDesigner. Cosa dovrebbe esserci al link sopra? Risulta una pagina vuota.
